### ISSUE TITLE
Variables description - less duplication

### ISSUE THREAD

**Issue by ccadruvi** [Lachlan-White/terraform-module-template#4]
Hey,

I like your module structure a lot, good work! One small thing I don't agree with (yet).

What's your opinion on the following?

In the variables.tf file, you list this as a good example:

```hcl
variable "virtual_machine_size" {
  description = "(Optional) The SKU which should be used for this Virtual Machine, such as Standard_F2. Defaults to 'Standard_D4s_v3'."
  type        = string
  default     = "Standard_D4s_v3"
}
```

1. I think there are two duplications in the description: the `(Optional)` can be inferred from whether a default value is set or not.
2. The default value is already documented.

If you use something like `terraform-docs`, this information would be duplicated in the README.

**Comment by Lachlan-White** [comment]
@ccadruvi - Totally agree there is some duplication here. I actually use this approach with `terraform-docs` and agree there is duplication. 

When it comes to the `(Optional)` I've found that it's pretty important to have this mentioned in the variable file so that a quick glance can tell you if it's required, rather than referring back to the documentation. I've also found that the use of this forces people to think about the treatment of the variable more in the context of another user.

The `defaults to x` component is a bit of duplication I agree with that. Will remove that from the description, again I don't mind it as it forces people to think but it is a tad redundant!
